# Generated by Django 5.2.9 on 2025-12-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy_ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partmaster',
            options={'ordering': ['part_number']},
        ),
        migrations.AlterField(
            model_name='partmaster',
            name='part_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
