# Generated by Django 5.2.9 on 2025-12-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy_ui', '0002_alter_partmaster_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partmaster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
