# Generated by Django 5.2.9 on 2025-12-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy_ui', '0003_alter_partmaster_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partmaster',
            options={},
        ),
        migrations.AlterField(
            model_name='partmaster',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='partmaster',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
